# Generated by dist/package/brew.sh -- do not edit manually.
# Update by pushing a new release tag to hamiorg/aura.
class Aura < Formula
  desc "AURA toolchain CLI -- compile .aura source to .atom/.hami/.atlas"
  homepage "https://hami.aduki.org"
  version "0.2.0-alpha.1"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/hamiorg/aura/releases/download/v0.2.0-alpha.1/aura-v0.2.0-alpha.1-macos-arm64.tar.gz"
      sha256 "948e15bbc930752891dbe9fa120fc740c5501a8a3ace7389b141c0a6da7bafb6"
    end

    on_intel do
      url "https://github.com/hamiorg/aura/releases/download/v0.2.0-alpha.1/aura-v0.2.0-alpha.1-macos-x86_64.tar.gz"
      sha256 "04eb24c17cf8d5db8b5ea9b0d296fc1e19b60a687dd53582abace7075c0d3c19"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/hamiorg/aura/releases/download/v0.2.0-alpha.1/aura-v0.2.0-alpha.1-linux-x86_64.tar.gz"
      sha256 "f05866ffdb68289594575a4863d0140681878ee8a93ab8b4f3b360fa40ccb61a"
    end

    on_arm do
      url "https://github.com/hamiorg/aura/releases/download/v0.2.0-alpha.1/aura-v0.2.0-alpha.1-linux-arm64.tar.gz"
      sha256 "a2d6c6cb7737d33c8e7b2a9564dbda44f74c6b7e676ca0b2c768dcf3c01c4ce9"
    end
  end

  def install
    bin.install "aura"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/aura --version")
  end
end
