# Generated by dist/package/brew.sh -- do not edit manually.
# Update by pushing a new release tag to hamiorg/aura.
class Aura < Formula
  desc "AURA toolchain CLI -- compile .aura source to .atom/.hami/.atlas"
  homepage "https://hami.aduki.org"
  version "0.1.0-alpha.1"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/hamiorg/aura/releases/download/v0.1.0-alpha.1/aura-v0.1.0-alpha.1-macos-arm64.tar.gz"
      sha256 "c918e3654d944fefa0957c1a9cc0e3a090954f6c3d37711899d5c4b677116a8c"
    end

    on_intel do
      url "https://github.com/hamiorg/aura/releases/download/v0.1.0-alpha.1/aura-v0.1.0-alpha.1-macos-x86_64.tar.gz"
      sha256 "a6179fc1c309ff0d12a6e23a5b49f621d3adcb80a6238f09894b62f84e966d71"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/hamiorg/aura/releases/download/v0.1.0-alpha.1/aura-v0.1.0-alpha.1-linux-x86_64.tar.gz"
      sha256 "da17bab6b2162181de66dad592262106aefc1a4f37aae7ca95d66b33050144db"
    end

    on_arm do
      url "https://github.com/hamiorg/aura/releases/download/v0.1.0-alpha.1/aura-v0.1.0-alpha.1-linux-arm64.tar.gz"
      sha256 "b9655573ce8443e6e63a66513a3ca7b860bcfe6a8438fb31061496d8b1d43b8a"
    end
  end

  def install
    bin.install "aura"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/aura --version")
  end
end
