# Generated by dist/package/brew.sh -- do not edit manually.
# Update by pushing a new release tag to hamiorg/aura.
class Aura < Formula
  desc "AURA toolchain CLI -- compile .aura source to .atom/.hami/.atlas"
  homepage "https://hami.aduki.org"
  version "0.3.3-beta.1"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/hamiorg/aura/releases/download/v0.3.3-beta.1/aura-v0.3.3-beta.1-macos-arm64.tar.gz"
      sha256 "a7ae1f8a28998c493f8137979596d921bff4cf1460eba7d16ba28c7f401dad60"
    end

    on_intel do
      url "https://github.com/hamiorg/aura/releases/download/v0.3.3-beta.1/aura-v0.3.3-beta.1-macos-x86_64.tar.gz"
      sha256 "d2d6e1f0d4e2ab0387db703bc9d2917116e328c91380798b45dbb5e19967bef5"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/hamiorg/aura/releases/download/v0.3.3-beta.1/aura-v0.3.3-beta.1-linux-x86_64.tar.gz"
      sha256 "5255addcbebf020306ea6ade780c074eb4687b7c959fe96487d43197460ef3fb"
    end

    on_arm do
      url "https://github.com/hamiorg/aura/releases/download/v0.3.3-beta.1/aura-v0.3.3-beta.1-linux-arm64.tar.gz"
      sha256 "6d13b8cc2245499b64b2899d584fb84af84ef41979ba62af26981bccf019024e"
    end
  end

  def install
    bin.install "aura"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/aura --version")
  end
end
